registry: test.registry.com
project: test-project
proxy:
  http: http://proxy.test.com:8080
  https: http://proxy.test.com:8080
  enabled: true
runtime:
  preferred: docker
  timeout: 10m
logging:
  level: debug
  format: text
  console: true
parallel:
  max_workers: 8
modes:
  save_mode: 2
  load_mode: 2
  push_mode: 2